### ISSUE TITLE
input type=file点确定后报错

### ISSUE THREAD

**Issue by ayaka209** [zsxsoft/cordova-plugin-x5-tbs#7]
懒得pr了……

X5WebChromeClient.java

257行改为：
Uri[] result =  android.webkit.WebChromeClient.FileChooserParams.parseResult(resultCode, intent);

因x5会报告
02-05 13:51:04.054 2990-2990/com.ztcrkj.app E/ReflectionUtils: 'com.tencent.smtt.webkit.FileChooserParamsAdapter' invoke static method 'parseFileChooserResult' failed
                                                               java.lang.ClassNotFoundException: Didn't find class "com.tencent.smtt.webkit.FileChooserParamsAdapter" on path: DexPathList[[zip file "/data/user/0/com.tencent.mm/app_tbs/core_share/tbs_jars_fusion_dex.jar"],nativeLibraryDirectories=[/data/user/0/com.tencent.mm/app_tbs/core_share, /data/user/0/com.tencent.mm/app_tbs/share/plugins/com.tencent.qb.plugin.videodecode, /system/lib, /vendor/lib]]
                                                                   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                   at com.tencent.common.utils.ReflectionUtils.a(Unknown Source)
                                                                   at com.tencent.common.utils.ReflectionUtils.invokeStaticMethod(Unknown Source)
                                                                   at com.tencent.tbs.tbsshell.WebCoreProxy.invokeStaticMethod(Unknown Source)
                                                                   at com.tencent.tbs.tbsshell.WebCoreProxy.parseFileChooserResult(Unknown Source)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.tencent.smtt.export.external.DexLoader.invokeStaticMethod(Unknown Source)
                                                                   at com.tencent.smtt.sdk.bl.a(Unknown Source)
                                                                   at com.tencent.smtt.sdk.WebChromeClient$FileChooserParams.parseResult(Unknown Source)
                                                                   at com.zsxsoft.cordova.x5.X5WebChromeClient$5.onActivityResult(X5WebChromeClient.java:257)
                                                                   at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:152)
                                                                   at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:358)
                                                                   at android.app.Activity.dispatchActivityResult(Activity.java:7125)
                                                                   at android.app.ActivityThread.deliverResults(ActivityThread.java:4186)
                                                                   at android.app.ActivityThread.handleSendResult(ActivityThread.java:4233)
                                                                   at android.app.ActivityThread.-wrap20(ActivityThread.java)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1606)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:163)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6365)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)
02-05 13:51:04.055 2990-2990/com.ztcrkj.app D/X5WebChromeClient: Receive file chooser URL: null

**Comment by ayaka209** [comment]
标题错了，其实是input type=file点确定后的错误

**Comment by zsxsoft** [comment]
好，我回头处理一下，感谢
